language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
- pypy
install:
- pip install -U pip
- pip install -e .[testing]
script:
- pytest
- pylint --rcfile=.pylintrc gossip tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: h+Pjy8kyp2b14/dnPqJul3azwrizEColFjC1VSahwbtWVRJ7w0uX0VT7ziOAARIMrxjS8cC/eJ6PGBGuFd0BXdTobK1danG/Wzqz6sV50bBGn1ZynzqxW+TIq7PSmLME4scUys1qpu5MTm4zxSDScYEU54mayhH/egoXtJD/o4I=
  on:
    tags: true
    repo: getslash/gossip
    branch: develop
